---
- name: Install required system packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - rolldice
    state: latest
    update_cache: true
  notify: Flag playbook changed


- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  notify: Flag playbook changed

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  notify: Flag playbook changed

- name: De-armor Docker GPG key for APT
  command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.gpg
  notify: Flag playbook changed

- name: Add Docker repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  notify: Flag playbook changed

- name: Update apt and install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  notify: Flag playbook changed

- name: Start and enable docker services
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  notify: Flag playbook changed

- name: Create docker-compose dir
  ansible.builtin.file:
    path: "{{ docker_compose_folder }}"
    state: directory
  notify: Flag playbook changed

- name: Copy Docker compose
  ansible.builtin.copy:
    src: compose/docker-compose.yml
    dest: "{{ docker_compose_folder }}/docker-compose.yml"
  notify: Flag playbook changed

- name: Deploy the Docker compose application
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_folder }}"
    state: present
  register: compose_result
  notify: Flag playbook changed

- name: Show compose compose_result
  ansible.builtin.debug:
        msg: "{{ compose_result }}"
